apiVersion: v1
kind: Service
metadata:
  name: advanced-react-services
  labels:
    app: advanced-react
spec: 
  selector:
    matchLabels:
      app: advanced-react
    ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
    